# @repo/{{name}}-sdk

OpenAPI-driven SDK generated by [kubb](https://kubb.dev).

## Update the spec

Replace `openapi/spec.yml` with the latest spec from upstream:

```bash
# pull a fresh copy from a URL
curl -fsSL <upstream-url> -o openapi/spec.yml
```

## Regenerate sources

```bash
bun --filter @repo/{{name}}-sdk generate
```

The output lives under `src/gen/` and is fully overwritten on each run.
Do not edit it by hand.

## Lint / format

```bash
bun --filter @repo/{{name}}-sdk lint
bun --filter @repo/{{name}}-sdk format
```
